### PR TITLE
Connections management

### PR DESCRIPTION
**Pull request by Samweli**
Fixes https://github.com/kartoza/qgis_geonode/issues/28

This work adds the first part of GeoNode connections management in the plugin, the changes include linking the new button in the main ui to load GeoNode connection dialog when clicked, creation of the new connection and saving the details using `QgsSettings` and listing up the available connections in the connection combo box.

Screenshot
connections_management

### CODE REVIEW

**Review by ricardogsilva — CHANGES_REQUESTED** [review]
A good start, but there are some things to improve upon:

- [x] UI does not look very pleasing to the eye - line edit widgets for Name and GeoNode URL should have similar length
- [x] Selected connection is not changed when adding a another one - even if your preview gif shows it is, I don't get that behavior on my local QGIS 3.16
- [x] Hook up the `Edit` button too in order to allow editing an existing connection - This is also in scope for the current issue
- [x] Hook up the `Remove` button too in order to allow removing an existing connection - This is also in scope for the current issue
- [ ] Use [QValidator](https://doc.qt.io/qt-5/qvalidator.html) for validating each connection detail
- [x] Disable the `OK` button until connection details are valid - As a general rule, protect the user from making bad choices, which in this case means not allowing to press OK until all connection details have valid input
- [ ] Using `"Qgis_GeoNode"` as the settings group name is wierd - use `"qgis_geonode"` (the plugin package's name) instead
- [ ] Store the auth config id in the `QgsSettings` too, in addition to name and geonode url
- [ ] Make the name of the settings group a constant. We will need to access settings from several places and typing down the name of the settings group is error-prone. Define a `SETTINGS_GROUP_NAME="qgis_geonode"` variable somewhere (perhaps in `qgisgeonode.main.py`?) and refer to that whenever you need to read/set stuff in the `QgsSettings` instance

**Comment by Samweli** [comment]
> * Store the auth config id in the `QgsSettings` too, in addition to name and geonode url

I have managed to store the auth config id, the challenge I have hade is set the authConfigSelect combo box index  to show the saved authentication configuration when editing connection, it seems there is no API for this..., see http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-QgsAuthConfigSelect-use-td5366701.html



> * Use [QValidator](https://doc.qt.io/qt-5/qvalidator.html) for validating each connection detail

I have validated only connection name so far, on URL validation what cases should we check?, It is a bit tricky to come up with a good regex that will cover all of the URL content.

**Comment by ricardogsilva** [comment]
> I have managed to store the auth config id, the challenge I have had is to set the QgsAuthConfigSelect combo box index to show the saved authentication configuration when editing connection, it seems there is no API for this

does the `QgsAuthConfigSelect.setConfigId()` not do this? I haven't tested it but it seems that this method would do what we need

**Comment by Samweli** [comment]
> does the `QgsAuthConfigSelect.setConfigId()` not do this?

It doesn't, in its implementation there is no place were it is updating the Authentication list combo box.

**Review by ricardogsilva — APPROVED** [review]
Seems to be all good now :smile:

**Pull request merged**
